version: '3.5'
services:
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: homeapi
      POSTGRES_USER: homeapi
      POSTGRES_DB: homeapi
    networks:
      - homeapi
networks:
  homeapi:
    name: homeapi
    driver: bridge
