version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:latest
    ports:
      - "443:443"
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-letsencrypt:/letsencrypt
    command:
      - --providers.docker=true
      - --accesslog=true
      - --accesslog.format=json
      - --log.level=DEBUG
      - --log.format=json
      - --providers.docker.network='webproxy'
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email='superd001@gmail.com'
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json

volumes:
  traefik-letsencrypt:

networks:
    default:
        external:
            name: webproxy
