providers:
  docker: 
    network: "webproxy"
  file:
    directory: /externals/

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesresolvers:
  le:
    acme:
      email: 'superd001@gmail.com'
      storage: 'acme.json'
      tlschallenge: true
      httpchallenge:
        entrypoint: web
