// Generated by https://quicktype.io

export interface LANHost {
  l2ident:             L2Ident;
  active:              boolean;
  id:                  string;
  last_time_reachable: number;
  persistent:          boolean;
  names:               Name[];
  vendor_name:         string;
  l3connectivities:    L3Connectivity[];
  reachable:           boolean;
  last_activity:       number;
  primary_name_manual: boolean;
  primary_name:        string;
}

export interface L2Ident {
  id:   string;
  type: string;
}

export interface L3Connectivity {
  addr:                string;
  active:              boolean;
  af:                  string;
  reachable:           boolean;
  last_activity:       number;
  last_time_reachable: number;
}

export interface Name {
  name:   string;
  source: string;
}
