version: '3'

services:
  diyhue:
    # The official v2 Traefik docker image
    image: diyhue/core:latest
    ports:
      - "1900:1900/udp"
      - "2100:2100/udp"
      - "1982:1982/udp"
    volumes:
      - diyhuevolume:/opt/hue-emulator/config
    environment:
      - MAC=AA:A4:DD:CB:0D:C9
      - IP=192.168.1.48
      - DEBUG=true
    mac_address: 02:42:C0:A8:84:64
    networks:
      10_vlan:
        priority: 100
      webproxy: ~
    labels:
      # Books is the actual calibre public web interface
      - traefik.docker.network=webproxy
      - traefik.http.routers.diyhue.entrypoints=websecure
      - traefik.http.routers.diyhue.rule=Host(`diyhue.home.davidfain.com`)
      - traefik.http.routers.diyhue.service=diyhue
      - traefik.http.routers.diyhue.tls=true
      - traefik.http.routers.diyhue.tls.certresolver=le
      - traefik.http.routers.diyhueunsecure.entrypoints=web
      - traefik.http.routers.diyhueunsecure.rule=Host(`diyhue.home.davidfain.com`)
      - traefik.http.routers.diyhueunsecure.service=diyhue
      - traefik.http.services.diyhue.loadbalancer.server.port=80
networks:
  10_vlan:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.64/32
  webproxy:
      name: webproxy
volumes:
  diyhuevolume: