name: Build & Deploy Apps

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: restore node cache
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: npm rebuild websocket
    - name: Reveal secrets
      uses: entrostat/git-secret-action@v3.3.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2      
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3
      with: 
        main-branch-name: 'master'
    - name: 'Build & push images'
      run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=2
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}