name: Build & Deploy Apps

on:
  push:
    branches: [ master ]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: restore node cache
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: npm rebuild websocket

  build:
    runs-on: ubuntu-latest
    needs: [ node ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: restore node cache
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - name: Reveal secrets
      uses: entrostat/git-secret-action@v3.3.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms:
          linux/arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2      
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3
      with: 
        main-branch-name: 'master'
    - name: "Login to registry"
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: superd22
        password: ${{ secrets.GH_REGISTRY_TOKEN }}
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: 'Build & push images'
      run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=1
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  stack:
    runs-on: ubuntu-latest
    needs: [ node ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: restore node cache
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - name: Reveal secrets
      uses: entrostat/git-secret-action@v3.3.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}   
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3
      with: 
        main-branch-name: 'master'
    - uses: arwynfr/actions-docker-context@v2
      with:
        docker_host: 'ssh://freebox@home.davidfain.com'
        context_name: 'freebox-remote'
        ssh_cert: ${{ secrets.SSH_CERT_HOME }}
        ssh_key: ${{ secrets.SSH_KEY_HOME }}
    - name: 'Resync infrastructure'
      run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=deploy --parallel=1
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}