name: Deploy unit files

on:
  push:
    branches: [ master ]
    paths: 
      - 'units/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: whoami
